# Generated by Django 4.2.2 on 2024-01-10 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('v_path', models.CharField(default='', max_length=200)),
                ('sub_path', models.CharField(default='', max_length=200)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
