# Generated by Django 4.2.2 on 2024-01-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Videos',
        ),
    ]
